{
 "title": "Maria DB Dashboard",
 "description": "My MySQL simple dashboard\r\nMariaDB Edition",
 "time": { "from": "2022-09-30T23:26:31.729Z", "to": "2022-10-28T23:26:31.729Z" },
 "templating": {
  "list": [
   { "name": "MyInstance", "query": "mysql" },
   {
    "name": "MyStatistics",
    "label": "Custom Statistic",
    "query": {
     "query": "select distinct variable_name from my2.status where variable_name is not null and variable_name <>'' order by 1"
    }
   },
   {
    "name": "MyVar",
    "query": {
     "query": "select concat( @@hostname,':', @@port)"
    }
   },
   {
    "name": "MyVar2",
    "query": {
     "query": "select concat('MySQL version: ',version(), '   Created at: ', date_format(min(create_time),'%Y-%m-%d %T') ,\n  '  Started at: ', date_format(date_sub(now(), INTERVAL variable_value second),'%Y-%m-%d %T')) info\n  from   information_schema.tables,information_schema.global_status\n where variable_name='UPTIME'\n group by variable_value\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">$MyInstance -- <b>$MyVar</b></div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  c1 AS \"time\",\n  v1\nFROM mylog\nWHERE\n  $__timeFilter(c1)\nORDER BY c1"
    }
   ]
  },
  {
   "title": "Connections/sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time_sec,\n  variable_value/600 as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  AND variable_name='CONNECTIONS-d'\n  AND variable_value>=0\nORDER BY timest ASC\n"
    }
   ]
  },
  {
   "title": "Threads & Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timest, '10m') AS time,\n       variable_name as metric,\n       avg(variable_value+0) as value\n  FROM my2.status\n WHERE $__timeFilter(timest)\n   AND variable_name in ('THREADS_CONNECTED', 'THREADS_RUNNING')\n GROUP BY 1,2\n ORDER BY 1 ASC"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(timest, '10m') as time,\n  substr(variable_name,1,length(variable_name)-2) as metric,\n  avg(variable_value+0) as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ('SLOW_QUERIES-d', 'ABORTED_CONNECTS-d','ABORTED_CLIENTS-d')\n  and variable_value>=0\nGROUP BY 1,2\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "Space usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timest,'24h') as time,\n  variable_name as metric,\n  avg(variable_value+0) as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ('SIZEDB.TOTAL')\nGROUP BY 1,2\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "InnoDB Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(s1.timest,'30m') as time_sec,\n  avg(1-s1.variable_value/s2.variable_value)*100 as value\nFROM my2.status s1,  my2.status s2\nWHERE $__timeFilter(s1.timest)\n  AND s1.timest=s2.timest\n  AND s1.variable_name='INNODB_BUFFER_POOL_READS-d'\n  AND s2.variable_name='INNODB_BUFFER_POOL_READ_REQUESTS-d'\n  AND s2.variable_value>0\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "MyISAM Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(s1.timest,'30m') as time_sec,\n  avg(1-s1.variable_value/s2.variable_value)*100 as value\nFROM my2.status s1,  my2.status s2\nWHERE $__timeFilter(s1.timest)\n  AND s1.timest=s2.timest\n  AND s1.variable_name='KEY_READS-d'\n  AND s2.variable_name='KEY_READ_REQUESTS-d'\n  AND s2.variable_value>0\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "SQL Commands /sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timest, '10m') AS time,\n       substr(variable_name,5,length(variable_name)-6) as metric,\n       avg(variable_value/600) as value\n  FROM my2.status\n WHERE $__timeFilter(timest)\n   and variable_name in ('COM_SELECT-d', 'COM_INSERT-d', 'COM_UPDATE-d', 'COM_DELETE-d')\n   and variable_value >=0\n GROUP BY 1,2\n ORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timest, '10m') AS time,\n       variable_name as metric,\n       avg(variable_value+0)/600 as value\n  FROM my2.status\n WHERE $__timeFilter(timest)\n   and variable_name in ('Bytes_received-d', 'Bytes_sent-d')\n GROUP BY 1,2\n ORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "Query Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(s1.timest,'30m') as time_sec,\n  avg((s1.variable_value/(s1.variable_value+s2.variable_value))*100) as value\nFROM my2.status s1,  my2.status s2\nWHERE $__timeFilter(s1.timest)\n  AND s1.timest=s2.timest\n  AND s1.variable_name='QCACHE_HITS-d'\n  AND s2.variable_name='COM_SELECT-d'\n  AND s2.variable_value>0\nGROUP BY 1\nORDER BY 1 ASC\n\n\n\n"
    }
   ]
  },
  {
   "title": "Master - Connected Slaves",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time_sec,\n  sum(variable_value+0) as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  AND variable_name like 'PROCESSES_COMMAND.Binlog Dump%'\nGROUP BY timest\nORDER BY timest ASC\n"
    }
   ]
  },
  {
   "title": "Custom Statistic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time,\n  variable_value+0 as value, variable_value/600 as value_sec,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(timest)\n  and variable_name in ($MyStatistics)\nORDER BY timest ASC\n"
    }
   ]
  },
  {
   "title": "Heatmap (Queries /sec)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timest, '24h') as time,\n  concat(' ',max(date_format(timest,'%H'))) as metric,\n  sum(variable_value)/3600 as value\nFROM my2.status\nWHERE variable_name='QUERIES-d'\n  and variable_value>0\n  and $__timeFilter(timest)\nGROUP BY $__timeGroup(timest, '1h'),$__timeGroup(timest, '24h')\nORDER BY 2, 1 \n"
    }
   ]
  },
  {
   "title": "Slave - IO Thread",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time_sec,\n  variable_value+0 as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  AND variable_name ='replication_connection_status'\nORDER BY timest ASC\n"
    }
   ]
  },
  {
   "title": "Slave - SQL Thread",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time_sec,\n  variable_value+0 as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  AND variable_name ='replication_applier_status'\nORDER BY timest ASC\n"
    }
   ]
  },
  {
   "title": "Slave - sec. behind Master",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timest) as time_sec,\n  variable_value+0 as value\nFROM my2.status\nWHERE $__timeFilter(timest)\n  AND (variable_name ='replication_worker_time' OR variable_name ='replication_max_worker_time')\nORDER BY timest ASC\n"
    }
   ]
  },
  {
   "title": "$MyVar2",
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  c1 AS \"time\",\n  v1\nFROM mylog\nWHERE\n  $__timeFilter(c1)\nORDER BY c1"
    }
   ]
  },
  {
   "title": "This dashboard uses my2 collector (https://github.com/meob/my2Collector)",
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 10, "y": 20 },
   "options": {
    "content": "<a href=\"https://github.com/meob/my2Collector\">Github</a>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  c1 AS \"time\",\n  v1\nFROM mylog\nWHERE\n  $__timeFilter(c1)\nORDER BY c1"
    }
   ]
  },
  {
   "title": "by XeniaLAB",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 20 },
   "options": {
    "content": "<a href=\"https://www.xenialab.it\">XeniaLAB</a>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  c1 AS \"time\",\n  v1\nFROM mylog\nWHERE\n  $__timeFilter(c1)\nORDER BY c1"
    }
   ]
  }
 ]
}