{
 "title": "Mongo DB Dashboard",
 "description": "A Mongodb Replication Performance Monitoring with Prometheus and telegraf agent",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "env", "query": { "query": "label_values(env)" } },
   {
    "name": "host",
    "query": {
     "query": "label_values(mongodb_inserts_per_sec{env=\"$env\"},host)"
    }
   },
   { "name": "inter", "label": "Interval", "query": "1m,10m,30m,1h,6h" },
   {
    "name": "prv_ip",
    "query": {
     "query": "label_values(mongodb_uptime_ns,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current master",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_inserts_per_sec{state=\"PRIMARY\"}"
    }
   ]
  },
  {
   "title": "Replication Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(mongodb_uptime_ns)" }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mem_used{host=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB UpTime ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mongodb_uptime_ns{host=~ \"$host\"}*10^-9)/3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{host=~ \"$host\",instance=~ \"$prv_ip:9273\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "Cpu Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{host=~ \"$host*\",cpu=\"cpu-total\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "mongo operations $host",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 15 },
   "repeat": "host",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "commands_per_sec $tag_host",
     "expr": "mongodb_inserts_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inserts ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"commands_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "commands_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "deletes_per_sec $tag_host",
     "expr": "mongodb_queries_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Queries ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"deletes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "deletes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "flushes_per_sec $tag_host",
     "expr": "mongodb_updates_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Updates",
     "measurement": "mongodb",
     "query": "SELECT mean(\"flushes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "flushes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "getmores_per_sec $tag_host",
     "expr": "mongodb_commands_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Commands",
     "measurement": "mongodb",
     "query": "SELECT mean(\"getmores_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "getmores_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "inserts_per_sec $tag_host",
     "expr": "mongodb_flushes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Flushes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"inserts_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "inserts_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "queries_per_sec $tag_host",
     "expr": "mongodb_getmores_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Getmores",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "queries_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "updates_per_sec $tag_host",
     "expr": "mongodb_deletes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deletes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "updates_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_active_reads{env=\"$env\",host=~\"$host\"}",
     "legendFormat": "Reads: {{host}}"
    }
   ]
  },
  {
   "title": "Current Writes Queue to Master",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_active_writes{env=\"$env\", state=\"PRIMARY\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_open_connections{env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Update Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_updates{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Insert Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_inserts{host=~ \"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Delete Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_deletes{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "replication oplog seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "mongodb_repl_oplog_window_sec", "legendFormat": "{{host}}" }
   ]
  }
 ]
}