{
 "title": "New_Oracle_Dashobard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Oracle_Instance_Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DBINSTANCE_APPLICATION_ID",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_APPLICATION_ID_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_DB_SIZE_GB_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_DB_SIZE_GB_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_DATABASE_SIZE_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_DATABASE_SIZE_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_BUFFER_GETS_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DBINSTANCE_BUFFER_GETS_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DBINSTANCE_APPLICATION_WAIT_TIME_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_APPLICATION_WAIT_TIME_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBINSTANCE_APPLICATION_WAIT_TIME_GAUGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DBINSTANCE_APPLICATION_WAIT_TIME_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Oracle_Runsituation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RUN_APPLICATION_WAIT_TIME",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "RUN_APPLICATION_WAIT_TIME_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RUN_COMMAND_TYPE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "targets": [
    { "expr": "RUN_COMMAND_TYPE_ORACLE_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RUN_CPU_TIME_MS_ORACLE_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUN_EXECUTIONS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "RUN_EXECUTIONS_ORACLE_GAUGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUN_PLSQL_EXEC_TIME",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "RUN_PLSQL_EXEC_TIME_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SQL Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_STATUS_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_SPL_PER_SEC_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLEANALYSISDATA_CPU_TIME",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "TABLEANALYSISDATA_CPU_TIME_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_ELAPSED_TIME",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_ELAPSED_TIME_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_EXECUTIONS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MOSTEXECUTE_EXECUTIONS_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_CPU_TIME",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_CPU_TIME_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_BUFFER_GETS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_BUFFER_GETS_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOSTEXECUTE_APPLICATION_WAIT_TIME",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "MOSTEXECUTE_APPLICATION_WAIT_TIME_ORACLE_GAUGE",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}