{
 "title": "Oracle Dashboard",
 "description": "Oracle simple dashboard",
 "tags": [
  "Oracle",
  "MyOra"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "MyInstance",
    "label": "Oracle Instance",
    "query": {
     "query": "select instance from my2.instance union select instance from my2.instance8x order by 1"
    }
   },
   {
    "name": "ver",
    "query": {
     "query": "select max(substr(variable_name, 9)) from my2.status where instance='$MyInstance' and variable_name like 'VERSION%'"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">$MyInstance</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timest as time, variable_value- lag(variable_value) over (order by timest)\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name in ('logons cumulative')\norder by time, variable_name"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timest as time, variable_name, variable_value\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name in ('SESSIONS_CONNECTED', 'SESSIONS_RUNNING', 'USER_SESSIONS')\norder by time, variable_name"
    }
   ]
  },
  {
   "title": "Space usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timest as time, 'Total Size' metric, variable_value\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name like 'SIZEDB.TOTAL'\norder by time, variable_name\n"
    }
   ]
  },
  {
   "title": "Tablespaces: Used Space",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT 0 as time, substr(variable_name,9,30), max(variable_value)\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name like 'SIZEEXT.%' \ngroup by variable_name\norder by 3"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timest as time, substr(variable_name, 11,30), variable_value\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name like 'PROCESSES.%'\norder by time, variable_name"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timest as time, variable_name, variable_value-lag(variable_value) over (PARTITION BY variable_name ORDER BY timest)\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name in ('user commits', 'user rollbacks')\norder by time, variable_name"
    }
   ]
  },
  {
   "title": "Hit ratio buffer cache",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT s1.timest as time, (1-s1.variable_value/(s2.variable_value+s3.variable_value))*100 as value\nfrom my2.status s1, my2.status s2, my2.status s3\nwhere s1.instance='$MyInstance'\n  and s2.instance='$MyInstance'\n  and s3.instance='$MyInstance'\n  and s1.timest=s2.timest\n  and s2.timest=s3.timest\n  and s1.variable_name='physical reads' \n  and s2.variable_name='db block gets' \n  and s3.variable_name='consistent gets'\n  and $__timeFilter(s1.timest)\n    and $__timeFilter(s2.timest)\n      and $__timeFilter(s3.timest)\norder by 1"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timest as time, variable_name, variable_value-lag(variable_value) over (PARTITION BY variable_name ORDER BY timest)\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name in ('bytes received via SQL*Net from client', 'bytes sent via SQL*Net to client')\norder by time, variable_name"
    }
   ]
  },
  {
   "title": "Heatmap (#Active)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', timest) as time,\n  ' ' || max(DATE_PART('hour',timest)) as metric,\n  max(variable_value) as value\nfrom my2.status\nwhere instance='$MyInstance'\n  and $__timeFilter(timest)\n  and variable_name in ('SESSIONS_RUNNING')\nGROUP BY date_trunc('hour', timest), date_trunc('day', timest)\nORDER BY 2, 1 "
    }
   ]
  },
  {
   "title": "SGA Components",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT 0 as time, substr(variable_name,5,30), max(variable_value)\nfrom my2.status\nwhere instance='$MyInstance'\n  and variable_name like 'SGA %' \n and $__timeFilter(timest)\ngroup by variable_name\norder by 3"
    }
   ]
  },
  {
   "title": "Oracle version: $ver",
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "This dashboard uses my4ora  collector (https://www.xenialab.it/meo/web/pub/my4ora-0.0.7.zip) [and some tricks ;] ",
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 10, "y": 20 },
   "targets": [
    {}
   ]
  }
 ]
}