{
 "title": "SQL Server Dashboard",
 "description": "Performance and health metrics for your SQL Servers.",
 "tags": [
  "influxdb",
  "SQL Server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"servername\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Databases properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DATABASES HEALTH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "State OFFLINE",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State ONLINE",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State OFFLINE",
     "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "SUSPECT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State SUSPECT",
     "query": "SELECT \"total\" FROM \"State SUSPECT\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "RECOVERING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State RECOVERING",
     "query": "SELECT \"total\" FROM \"State RECOVERING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "PENDING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State RECOVERY_PENDING",
     "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "RESTORING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "State RESTORING",
     "query": "SELECT \"total\" FROM \"State RESTORING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "RPO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Performance metrics",
     "query": "SELECT \"Point In Time Recovery\" FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter",
     "select": [
      [
       { "params": [ "Point In Time Recovery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "FULL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Recovery Model FULL",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "BULK LOGGED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Recovery Model BULK_LOGGED",
     "query": "SELECT \"total\" FROM \"Recovery Model BULK_LOGGED\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "SIMPLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Recovery Model SIMPLE",
     "query": "SELECT \"total\" FROM \"Recovery Model SIMPLE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "KPI | CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Idle (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SystemIdle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "SQL CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "External CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "External process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Signal Wait (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"Signal wait (%)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "External process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Average tasks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"Average tasks\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "External process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Runnage Tasks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"Average runnable tasks\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "External process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "KPI | Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Target Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Target Server Memory (KB) | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Target Server Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Total Server Memory (KB) | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Total Server Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Used/Target Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Total target memory ratio\") FROM \"Performance metrics\" WHERE \"type\" = 'Performance metrics' AND \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Total target memory ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Performance metrics" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Page File",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Page File Usage (%)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Page File Usage (%)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "PLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Page life expectancy | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page life expectancy | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pool Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Buffer pool rate (bytes/sec)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Buffer pool rate (bytes/sec)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Free List Stalls/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Free list stalls/sec | Buffer Manager",
     "query": "SELECT \"value\" FROM \"Free list stalls/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Memory Grant Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory Grants Pending | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Memory Grants Pending | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "KPI | I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rows Reads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Rows reads (bytes/sec)",
     "query": "SELECT mean(\"Total\") FROM \"Rows reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Log Reads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log reads (bytes/sec)",
     "query": "SELECT mean(\"Total\") FROM \"Log reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Rows Writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Rows writes (bytes/sec)",
     "query": "SELECT mean(\"Total\") FROM \"Rows writes (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Log Writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log writes (bytes/sec)",
     "query": "SELECT mean(\"Total\") FROM \"Log writes (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Pending I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Average pending disk IO\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Average pending disk IO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Network IO waits | Average wait time (ms) | Wait Statistics",
     "query": "SELECT \"value\" FROM \"Network IO waits | Average wait time (ms) | Wait Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "KPI | Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "User Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "User Connections | General Statistics",
     "query": "SELECT mean(\"value\") FROM \"User Connections | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Per Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Connection memory per connection (bytes)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Connection memory per connection (bytes)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Data File Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Data File(s) Size (KB) | _Total | Databases",
     "query": "SELECT \"value\" FROM \"Data File(s) Size (KB) | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "System Data File Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Data File(s) Size (KB) | mssqlsystemresource | Databases",
     "query": "SELECT \"value\" FROM \"Data File(s) Size (KB) | mssqlsystemresource | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Log used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Percent Log Used | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Percent Log Used | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "System Log used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Percent Log Used | mssqlsystemresource | Databases",
     "query": "SELECT mean(\"value\") FROM \"Percent Log Used | mssqlsystemresource | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Backup/Restore Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Backup/Restore Throughput/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Backup/Restore Throughput/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Performance counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SQL Server Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Batch Requests/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Batch Requests/sec | SQL Statistics",
     "query": "SELECT mean(\"value\") FROM \"Batch Requests/sec | SQL Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "User Connections",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "User Connections | General Statistics",
     "query": "SELECT mean(\"value\") FROM \"User Connections | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Logins/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Logins/sec | General Statistics",
     "query": "SELECT mean(\"value\") FROM \"Logins/sec | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Logouts/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Logouts/sec | General Statistics",
     "query": "SELECT mean(\"value\") FROM \"Logouts/sec | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "SQL Compilations/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQL Compilations/sec | SQL Statistics",
     "query": "SELECT mean(\"value\") FROM \"SQL Compilations/sec | SQL Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "SQL Re-Compilations/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SQL Re-Compilations/sec | SQL Statistics",
     "query": "SELECT mean(\"value\") FROM \"SQL Re-Compilations/sec | SQL Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Processes blocked",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Processes blocked | General Statistics",
     "query": "SELECT mean(\"value\") FROM \"Processes blocked | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Databases Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Transactions/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Transactions/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Transactions/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Write Transactions/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Write Transactions/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Write Transactions/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Flushes/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log Flushes/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Log Flushes/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Flush Wait Time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log Flush Wait Time | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Log Flush Wait Time | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lock Timeouts/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Lock Timeouts/sec | _Total | Locks",
     "query": "SELECT mean(\"value\") FROM \"Lock Timeouts/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Number of Deadlocks/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Number of Deadlocks/sec | _Total | Locks",
     "query": "SELECT mean(\"value\") FROM \"Number of Deadlocks/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lock Waits/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Lock Waits/sec | _Total | Locks",
     "query": "SELECT mean(\"value\") FROM \"Lock Waits/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Latch Waits/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Latch Waits/sec | Latches",
     "query": "SELECT mean(\"value\") FROM \"Latch Waits/sec | Latches\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Cache - Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Full Scans/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Full Scans/sec | Access Methods",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Index Searches/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Index Searches/sec | Access Methods",
     "query": "SELECT mean(\"value\") FROM \"Index Searches/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page Splits/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Page Splits/sec | Access Methods",
     "query": "SELECT mean(\"value\") FROM \"Page Splits/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page lookups/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Page lookups/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page lookups/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page reads/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Page reads/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page reads/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Page writes/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Page writes/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page writes/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Readahead pages/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Readahead pages/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Readahead pages/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lazy writes/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Lazy writes/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Lazy writes/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Checkpoint pages/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Checkpoint pages/sec | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Checkpoint pages/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "SQL Cache",
     "measurement": "SQL Cache Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"SQL Cache Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Optimizer",
     "measurement": "Optimizer Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Optimizer Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Pool",
     "measurement": "Log Pool Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Log Pool Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Lock",
     "measurement": "Lock Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Lock Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Database Cache",
     "measurement": "Database Cache Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Database Cache Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Connection",
     "measurement": "Connection Memory (KB) | Memory Manager",
     "query": "SELECT \"value\" FROM \"Connection Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Log activities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Log Flushes/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log Flushes/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Pool Cache Misses/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log Pool Cache Misses/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Pool Disk Reads/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log Pool Disk Reads/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    },
    {
     "alias": "Log Pool Requests/sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Log Pool Requests/sec | _Total | Databases",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Waits Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wait Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Wait time (ms)",
     "query": "SELECT \"Buffer\", \"CLR\", \"I/O\", \"Latch\", \"Lock\", \"Memory\", \"Network\", \"Service broker\", \"Other\", \"SQLOS\", \"XEvent\" FROM \"Wait time (ms)\" WHERE \"type\" = 'Wait stats' AND \"servername\" =~ /$Instance$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Buffer" ], "type": "field" }
      ],
      [
       { "params": [ "CLR" ], "type": "field" }
      ],
      [
       { "params": [ "I/O" ], "type": "field" }
      ],
      [
       { "params": [ "Latch" ], "type": "field" }
      ],
      [
       { "params": [ "Lock" ], "type": "field" }
      ],
      [
       { "params": [ "Memory" ], "type": "field" }
      ],
      [
       { "params": [ "Network" ], "type": "field" }
      ],
      [
       { "params": [ "Service broker" ], "type": "field" }
      ],
      [
       { "params": [ "Other" ], "type": "field" }
      ],
      [
       { "params": [ "SQLOS" ], "type": "field" }
      ],
      [
       { "params": [ "XEvent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Wait stats" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Wait Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Wait tasks",
     "query": "SELECT \"Buffer\", \"CLR\", \"I/O\", \"Latch\", \"Lock\", \"Memory\", \"Network\", \"Service broker\", \"Other\", \"SQLOS\", \"XEvent\" FROM \"Wait tasks\" WHERE \"type\" = 'Wait stats' AND \"servername\" =~ /$Instance$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Buffer" ], "type": "field" }
      ],
      [
       { "params": [ "CLR" ], "type": "field" }
      ],
      [
       { "params": [ "I/O" ], "type": "field" }
      ],
      [
       { "params": [ "Latch" ], "type": "field" }
      ],
      [
       { "params": [ "Lock" ], "type": "field" }
      ],
      [
       { "params": [ "Memory" ], "type": "field" }
      ],
      [
       { "params": [ "Network" ], "type": "field" }
      ],
      [
       { "params": [ "Service broker" ], "type": "field" }
      ],
      [
       { "params": [ "Other" ], "type": "field" }
      ],
      [
       { "params": [ "SQLOS" ], "type": "field" }
      ],
      [
       { "params": [ "XEvent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Wait stats" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory break down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Memory breakdown (%)",
     "query": "SELECT * FROM \"Memory breakdown (%)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Memory clerk' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Memory clerk" }
     ]
    }
   ]
  },
  {
   "title": "Memory (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Memory breakdown (bytes)",
     "query": "SELECT * FROM \"Memory breakdown (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Database size trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database | Rows Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Rows size (bytes)",
     "query": "SELECT * FROM \"Rows size (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database size' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database size" }
     ]
    }
   ]
  },
  {
   "title": "Database | Log Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Log size (bytes)",
     "query": "SELECT * FROM \"Log size (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database size' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database size" }
     ]
    }
   ]
  },
  {
   "title": "Database I/O | READ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads | Rows Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Rows reads (bytes/sec)",
     "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Rows reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Reads | Log Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Log reads (bytes/sec)",
     "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Log reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Database I/O | WRITE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Writes | Rows Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Rows writes (bytes/sec)",
     "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Rows writes (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Writes | Log Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Log writes (bytes/sec)",
     "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Log writes (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
     ]
    }
   ]
  },
  {
   "title": "Database Latency | READ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads | Rows (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Rows read latency (ms)",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
     ]
    }
   ]
  },
  {
   "title": "Reads | Log (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Log read latency (ms)",
     "query": "SELECT * FROM \"Log read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
     ]
    }
   ]
  },
  {
   "title": "Database Latency | WRITE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Writes | Rows (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Rows write latency (ms)",
     "query": "SELECT * FROM \"Rows write latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
     ]
    }
   ]
  },
  {
   "title": "Writes | Log (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Log write latency (ms)",
     "query": "SELECT * FROM \"Log write latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
     ]
    }
   ]
  },
  {
   "title": "OS VOLUME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Volume used space (bytes)",
     "query": "SELECT * FROM \"Volume used space (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'OS Volume space' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "OS Volume space" }
     ]
    }
   ]
  },
  {
   "title": "Available bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Volume available space (bytes)",
     "query": "SELECT * FROM \"Volume available space (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'OS Volume space' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "OS Volume space" }
     ]
    }
   ]
  },
  {
   "title": "Used (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "Volume used space (%)",
     "query": "SELECT * FROM \"Volume used space (%)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'OS Volume space' AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "OS Volume space" }
     ]
    }
   ]
  },
  {
   "title": "Used",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 102 },
   "targets": [
    {
     "alias": "$col",
     "application": { "filter": "" },
     "group": { "filter": "MS SQL Server" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Volume used space (%)",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT \"C:\", \"D: (DATA)\", \"L: (LOG)\", \"T: (TEMPDB)\" FROM \"Volume used space (%)\" WHERE \"servername\" =~ /$Instance$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "D: (DATA)" ], "type": "field" }
      ],
      [
       { "params": [ "L: (LOGS)" ], "type": "field" }
      ],
      [
       { "params": [ "T: (TEMPDB)" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "OTHERS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ratios",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pages split/batch request",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Page split per batch request\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Page split per batch request" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    },
    {
     "alias": "SQL Compilation/batch request",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Sql compilation per batch request\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Sql compilation per batch request"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    },
    {
     "alias": "SQL Recompilation/batch request",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Sql recompilation per batch request\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Sql recompilation per batch request"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    },
    {
     "alias": "Read-ahead/page read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Readahead per page read\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Readahead per page read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SQL Server",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"SQL process\") FROM \"CPU (%)\" WHERE \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    },
    {
     "alias": "External process",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"External process\") FROM \"CPU (%)\" WHERE \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "External process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Availability Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OUT | Bytes sent to Replica/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Bytes Sent to Replica/sec | _Total | Availability Replica",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Performance counters" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "IN | Bytes received from Replica/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Bytes Received from Replica/sec | _Total | Availability Replica",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Performance counters" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Transaction Delay | _Total | Database Replica",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Performance counters" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Mirrored Write Transactions/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Mirrored Write Transactions/sec | _Total | Database Replica",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Performance counters" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  }
 ]
}